const ARQSELECT_CONFIG={API_URL:localStorage.getItem("ARQSELECT_API_URL")||"https://script.google.com/macros/s/AKfycbz_jLzNa87U_himraaCczzqGpQdq63AyIVogQ9-YGnqXuQYl3OSJfV4E7xYfPdnv8-d/exec",POLL_MS:15000};
const qs=new URLSearchParams(location.search);
function apiGet(a,p={}){const u=new URL(ARQSELECT_CONFIG.API_URL);u.searchParams.set("acao",a);Object.entries(p).forEach(([k,v])=>v!=null&&u.searchParams.set(k,v));return fetch(u).then(r=>r.json()).catch(e=>({sucesso:false,mensagem:e.message}))}
function apiPost(a,d={}){const body=new URLSearchParams({acao:a,...d});return fetch(ARQSELECT_CONFIG.API_URL,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body}).then(r=>r.json()).catch(e=>({sucesso:false,mensagem:e.message}))}
function getSession(){try{return JSON.parse(localStorage.getItem("ARQSELECT_SESSION")||"null")}catch(e){return null}}function setSession(s){localStorage.setItem("ARQSELECT_SESSION",JSON.stringify(s))}function clearSession(){localStorage.removeItem("ARQSELECT_SESSION")}
function requireAuth(role){const s=getSession();if(!s?.token){location.href="login.html";return null}if(role&&s.usuario?.PERFIL!==role&&s.usuario?.PERFIL!=="ADMIN"){location.href="login.html";return null}return s}
function fmtBRL(v){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#39;"}[c]))}
function toast(m){let x=document.querySelector(".toast");if(!x){x=document.createElement("div");x.className="toast";document.body.appendChild(x)}x.textContent=m;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),3000)}
function logout(){const s=getSession();if(s?.token)apiPost("logout_v2",{token:s.token});clearSession();location.href="login.html"}function bindLogout(){document.querySelectorAll("[data-logout]").forEach(x=>x.onclick=e=>{e.preventDefault();logout()})}
function layout(title,role){document.title=title+" • ARQSELECT";const s=requireAuth(role);if(!s)return;document.querySelectorAll("[data-user]").forEach(x=>x.textContent=s.usuario?.NOME||s.usuario?.LOGIN||"");bindLogout();return s}
