(function(){
'use strict';document.documentElement.classList.add('arq-premium-ui');
const CFG=window.ARQSELECT_CONFIG||{},cats=['portas','pisos','revestimentos','madeira','marcenaria','esquadrias','pedras','iluminacao','moveis','automacao','loucas','metais','decoracao','construcao','vidros','paisagismo','climatizacao'];
const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=v=>String(v||'').split(',')[0].trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const pending=new Map(),cache=new Map();
function fallback(category){const s=slug(category);return cats.includes(s)?'assets/categories/fallback-'+s+'.webp':'assets/ui/fallback-geral.svg';}
function resolve(raw){const s=String(raw||'').trim();if(!s||/(?:\.\.|%2e%2e|%2e\.|\.%2e)/i.test(s))return '';if(/^(data:image\/(png|jpeg|webp);base64,|blob:)/i.test(s))return s;if(/^(assets\/|[a-z0-9][a-z0-9_.-]*\.(avif|webp|png|jpe?g|svg)$)/i.test(s)&&!s.includes('..'))return (CFG.mediaBaseUrl&&s.startsWith('assets/')?CFG.mediaBaseUrl.replace(/\/$/,'')+'/':'')+s;
try{const u=new URL(s,location.href);if(u.origin===location.origin&&/\.(avif|webp|png|jpe?g|svg)$/i.test(u.pathname))return u.href;if(CFG.mediaBaseUrl&&u.href.startsWith(CFG.mediaBaseUrl.replace(/\/$/,'')+'/'))return u.href;}catch(_){}return '';}
function attributes(raw,category,alternates=[]){const ref=String(raw||'');return `src="${esc(resolve(ref)||fallback(category))}" data-category="${esc(category||'')}"${ref.startsWith('arqmedia:')?` data-arq-ref="${esc(ref)}"`:''} data-arq-alternates="${esc(JSON.stringify(alternates))}"`;}
async function loadMedia(ref){if(cache.has(ref))return cache.get(ref);if(pending.has(ref))return pending.get(ref);const job=(async()=>{const token=(/admin/i.test(location.pathname)?localStorage.getItem('ARQSELECT_ADMIN_TOKEN'):localStorage.getItem('ARQSELECT_PORTAL_TOKEN'))||localStorage.getItem('ARQSELECT_ADMIN_TOKEN')||'';const c=new AbortController();const timer=setTimeout(()=>c.abort(),20000);try{const r=await fetch(CFG.apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({acao:'portal_media',ref,token}),signal:c.signal});const j=await r.json(),d=j.data||j;if(!j.sucesso||!/^image\/(jpeg|png|webp)$/.test(d.mime)||!d.base64)throw Error('Mídia indisponível');const bytes=Uint8Array.from(atob(d.base64),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:d.mime}));cache.set(ref,url);return url;}finally{clearTimeout(timer);}})();pending.set(ref,job);try{return await job;}finally{pending.delete(ref);}}
function handleError(img,category){if(!img)return;img.removeAttribute('srcset');img.closest('picture')?.querySelectorAll('source').forEach(s=>s.removeAttribute('srcset'));let refs=[];try{refs=JSON.parse(img.dataset.arqAlternates||'[]');}catch(_){}const tried=JSON.parse(img.dataset.arqTried||'[]');const candidates=[...refs,fallback(category),'assets/ui/fallback-geral.svg'].map(resolve).filter(Boolean);const next=candidates.find(x=>!tried.includes(x)&&x!==img.getAttribute('src'));if(next){img.dataset.arqTried=JSON.stringify([...tried,img.getAttribute('src'),next]);img.src=next;}else{img.removeAttribute('src');img.style.visibility='hidden';img.parentElement?.classList.add('arq-media-fallback');}}
function hydrate(root=document){root.querySelectorAll('img').forEach(img=>{if(!img.hasAttribute('alt'))img.alt=img.dataset.category||'Referência de arquitetura';img.decoding='async';if(!img.hasAttribute('loading'))img.loading='lazy';const raw=img.getAttribute('src')||'';if(raw.startsWith('arqmedia:')){img.dataset.arqRef=raw;img.src=fallback(img.dataset.category);}else if(raw&&!resolve(raw)){img.src=fallback(img.dataset.category);img.removeAttribute('srcset');}if(img.dataset.arqRef&&!img.dataset.arqLoading){img.dataset.arqLoading='1';loadMedia(img.dataset.arqRef).then(url=>{if(img.isConnected)img.src=url;}).catch(()=>handleError(img,img.dataset.category));}});}
window.ARQSELECT_MEDIA={categorySlug:slug,fallback,resolve,attributes,hydrate,handleError,getProductImage:p=>p.imagem_card||p.imagem_principal||fallback(p.categoria||p.CATEGORIA),getCatalogImage:c=>c['CAPA URL']||c.capa||fallback(c.CATEGORIAS||c.categorias),getSupplierImage:s=>s.LOGO||s.logo||s.foto||'assets/suppliers/identidade-pendente.svg'};
document.addEventListener('error',e=>{if(e.target.tagName==='IMG')handleError(e.target,e.target.dataset.category);},true);
function init(){hydrate();const nav=document.querySelector(".nav,.sidebar,.arq-header-actions");if(nav&&(localStorage.getItem('ARQSELECT_PORTAL_TOKEN')||localStorage.getItem('ARQSELECT_ADMIN_TOKEN'))&&!/login/i.test(location.pathname)&&!document.querySelector('a[href="solicitacoes-marketplace.html"]')){const link=document.createElement("a");link.href="solicitacoes-marketplace.html"+(/admin/i.test(location.pathname)?"?perfil=admin":"");link.textContent="Solicitações";link.className="arq-requests-link";nav.append(link);}let scheduled=false;new MutationObserver(()=>{if(!scheduled){scheduled=true;requestAnimationFrame(()=>{scheduled=false;hydrate();});}}).observe(document.body,{childList:true,subtree:true});
if(document.body.dataset.noWhatsapp==='1'||/admin|login/i.test(location.pathname)||document.querySelector('.arq-whatsapp-float,.arq-global-wa,.wa-float'))return;const a=document.createElement('a');a.className='arq-global-wa';a.target='_blank';a.rel='noopener';a.href='https://wa.me/'+(CFG.whatsapp||'5519981655013')+'?text='+encodeURIComponent('Vim pelo site da ARQSELECT e gostaria de falar sobre meu projeto.');a.setAttribute('aria-label','WhatsApp ARQSELECT, (19) 98165-5013');a.innerHTML='<svg viewBox="0 0 24 24" width="24" height="24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20.5 11.5a8.5 8.5 0 0 1-12.7 7.4L3 20l1.2-4.6A8.5 8.5 0 1 1 20.5 11.5Z"/><path d="M8 7c-2 3 3 8 6 8l2-2-3-1-1 1-2-2 1-1-1-3Z"/></svg><span>WhatsApp ARQSELECT<small>(19) 98165-5013</small></span>';document.body.append(a);}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
