/* Download de anexos privados, autorizado pelo vínculo ao projeto ou proposta. */
(function(){'use strict';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function fileId(url){try{const u=new URL(url,location.href);if(!['drive.google.com','docs.google.com'].includes(u.hostname))return '';return (u.pathname.match(/\/d\/([A-Za-z0-9_-]+)/)||[])[1]||u.searchParams.get('id')||'';}catch(_){return '';}}
 function links(value,type,id){let items;try{items=Array.isArray(value)?value:JSON.parse(value||'[]');}catch(_){items=[];}if(!Array.isArray(items))return '';return items.map(f=>{const key=f.id||fileId(f.url);return key?`<button type="button" class="btn" data-arq-anexo="${esc(type)}" data-registro="${esc(id)}" data-arquivo="${esc(key)}">Baixar ${esc(f.nome||'anexo')}</button>`:'';}).join('');}
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-arq-anexo]');if(!b)return;const id=b.dataset.arquivo||fileId(b.getAttribute('href'));if(!id)return;e.preventDefault();if(b.getAttribute('aria-busy')==='true')return;b.setAttribute('aria-busy','true');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);
 try{const admin=/admin/i.test(location.pathname)||new URLSearchParams(location.search).get('perfil')==='admin';const token=admin?localStorage.getItem('ARQSELECT_ADMIN_TOKEN'):localStorage.getItem('ARQSELECT_PORTAL_TOKEN')||localStorage.getItem('ARQSELECT_ADMIN_TOKEN');const r=await fetch(window.ARQSELECT_CONFIG.apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify({acao:'portal_anexo_arquivo',token,tipo:b.dataset.arqAnexo,id:b.dataset.registro,arquivoId:id}),signal:controller.signal});if(!r.ok)throw Error('Não foi possível carregar o anexo.');const j=await r.json();if(!j.sucesso)throw Error(j.mensagem||'Anexo indisponível.');const d={...(j.data||{}),...j},bytes=Uint8Array.from(atob(d.base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:d.mime||'application/octet-stream'})),a=document.createElement('a');a.href=url;a.download=String(d.nome||'anexo').replace(/[\\/]/g,'-');document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);
 }catch(err){alert(err.name==='AbortError'?'O download demorou mais que o esperado. Tente novamente.':err.message);}finally{clearTimeout(timer);b.removeAttribute('aria-busy');}});
 window.ARQSELECT_ATTACHMENTS={links};
})();
