(function(){
'use strict';
const A=()=>window.ARQSELECT6,$=s=>document.querySelector(s),token=()=>localStorage.getItem('ARQSELECT_PORTAL_TOKEN')||'',esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=(action,data={},method='GET')=>A()?.api?A().api(action,{...data,token:token()},method):Promise.resolve({sucesso:false,mensagem:'API indisponível'});
const EVENTS=[['NOVA_SOLICITACAO','Nova solicitação'],['NOVA_PROPOSTA','Nova proposta'],['NOVA_MENSAGEM','Nova mensagem'],['NOVA_OPORTUNIDADE','Nova oportunidade'],['PROJETO_ATUALIZADO','Projeto atualizado'],['NOVO_COMENTARIO','Novo comentário'],['NOVA_CONEXAO','Nova conexão'],['PRODUTO_RECOMENDADO','Produto recomendado']];
function toast(m,tone='info'){window.ARQSELECT_UI?.toast?.(m,{tone})}
async function notifications(){
 const host=$('#notificationPrefs');if(!host)return;host.innerHTML='<div class="arq6-empty">Carregando preferências…</div>';
 const r=await api('portal_preferencias_notificacao'),map={};(r.preferencias||[]).forEach(x=>map[String(x.EVENTO||'').toUpperCase()]=x);
 host.innerHTML='<div class="arq-account-events">'+EVENTS.map(([key,label])=>{const p=map[key]||{};return '<form class="arq-account-event" data-event="'+key+'"><div><b>'+label+'</b><small>Escolha como deseja receber este tipo de atualização.</small></div><label><input type="checkbox" name="interno" '+(p.INTERNO!=='NAO'?'checked':'')+'> Interno</label><label><input type="checkbox" name="email" '+(p.EMAIL!=='NAO'?'checked':'')+'> E-mail</label><label><input type="checkbox" name="whatsapp" '+(p.WHATSAPP==='SIM'?'checked':'')+'> WhatsApp</label><select name="frequencia" aria-label="Frequência"><option value="IMEDIATA" '+(p.FREQUENCIA==='IMEDIATA'?'selected':'')+'>Imediata</option><option value="RESUMO_DIARIO" '+(p.FREQUENCIA==='RESUMO_DIARIO'?'selected':'')+'>Resumo diário</option><option value="DESATIVADA" '+(p.FREQUENCIA==='DESATIVADA'?'selected':'')+'>Desativada</option></select><button class="arq6-btn" type="submit">Salvar</button></form>'}).join('')+'</div>';
 host.querySelectorAll('form').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const d=new FormData(f),rr=await api('portal_preferencias_notificacao_salvar',{evento:f.dataset.event,interno:d.has('interno'),email:d.has('email'),whatsapp:d.has('whatsapp'),frequencia:d.get('frequencia')},'POST');toast(rr.mensagem||'Preferência atualizada.',rr.sucesso?'success':'error')});
}
async function completeness(){const host=$('#profileCompleteness');if(!host)return;const r=await api('portal_perfil_completude');if(!r.sucesso){host.hidden=true;return}host.innerHTML='<div class="arq-account-complete"><div><b>Perfil '+Number(r.completude||0)+'% completo</b><span>'+(r.faltando||[]).length?'Itens pendentes: '+esc((r.faltando||[]).join(', ')):'Seu perfil possui os dados essenciais.'+'</span></div><div class="arq-progress"><i style="width:'+Math.max(0,Math.min(100,Number(r.completude||0)))+'%"></i></div></div>'}
function exportData(){const b=$('#exportMyData');if(!b)return;b.onclick=async()=>{b.disabled=true;const r=await api('portal_exportar_meus_dados');b.disabled=false;if(!r.sucesso)return toast(r.mensagem||'Não foi possível exportar.','error');const blob=new Blob([JSON.stringify(r.exportacao||{},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='arqselect-meus-dados-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Exportação gerada.','success')}}
function consent(){const b=$('#privacyConsent');if(!b)return;b.onclick=async()=>{const r=await api('portal_consentimento_salvar',{tipo:'PRIVACIDADE',versao:'6.0',aceito:true,origem:'CONFIGURACOES'},'POST');toast(r.mensagem||'Preferência registrada.',r.sucesso?'success':'error')}}
function feedback(){const f=$('#accountFeedback');if(!f)return;f.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f)),b=f.querySelector('button');b.disabled=true;const r=await api('portal_feedback_salvar',{...d,pagina:location.pathname,contexto:{role:localStorage.getItem('ARQSELECT_PORTAL_TIPO')||''}},'POST');b.disabled=false;toast(r.mensagem||'Feedback registrado.',r.sucesso?'success':'error');if(r.sucesso)f.reset()}}
function init(){if(!token())return;notifications();completeness();exportData();consent();feedback()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();