(function(){
  'use strict';
  if(window.ARQSELECT6)return;
  const C=window.ARQSELECT_CONFIG||{};
  const apiUrl=()=>window.ARQSELECT_API_URL||C.apiUrl||C.API_URL||'';
  const token=()=>localStorage.getItem('ARQSELECT_PORTAL_TOKEN')||'';
  const role=()=>String(localStorage.getItem('ARQSELECT_PORTAL_TIPO')||'').toUpperCase();
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function toast(message,options){if(window.ARQSELECT_UI?.toast)return window.ARQSELECT_UI.toast(message||'',options||{});let t=document.getElementById('arq6Toast');if(!t){t=document.createElement('div');t.id='arq6Toast';t.className='arq6-toast';document.body.append(t);}t.textContent=message||'';t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),3000);}
  async function api(action,data={},method='GET'){
    if(window.ARQSELECT4?.api)return window.ARQSELECT4.api(action,data,method);
    const base=apiUrl();if(!base)return {sucesso:false,mensagem:'API indisponível.'};
    const payload={acao:action,...data};
    try{if(method==='POST'){const r=await fetch(base,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify(payload)});return await r.json();}const u=new URL(base);Object.entries(payload).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')u.searchParams.set(k,typeof v==='object'?JSON.stringify(v):String(v));});const r=await fetch(u,{cache:'no-store'});return await r.json();}catch(e){return {sucesso:false,mensagem:'Não foi possível conectar à ARQSELECT.'};}
  }
  function sessionId(){let id=localStorage.getItem('ARQSELECT_ANALYTICS_SESSION');if(!id){id=(crypto.randomUUID?.()||String(Date.now())+Math.random()).replace(/[^a-z0-9-]/gi,'');localStorage.setItem('ARQSELECT_ANALYTICS_SESSION',id);}return id;}
  function track(event,module,record,value){return api('portal_evento_analytics',{evento:event,modulo:module,registroId:record,valor:value||'',sessionId:sessionId(),origem:location.pathname.split('/').pop()},'POST').catch(()=>{});}
  function modal(title,body){let root=document.getElementById('arq6Modal');if(!root){root=document.createElement('div');root.id='arq6Modal';root.className='arq6-modal';root.hidden=true;document.body.append(root);}root.innerHTML=`<div class="arq6-modal-card"><div class="arq6-modal-head"><div><div class="arq6-kicker">ARQSELECT</div><h2>${esc(title)}</h2></div><button class="arq6-btn" data-close aria-label="Fechar">×</button></div><div data-body>${body}</div></div>`;root.hidden=false;root.onclick=e=>{if(e.target===root||e.target.closest('[data-close]'))root.hidden=true;};return root.querySelector('[data-body]');}
  async function chooseProject(onChoose){const r=await api('portal_projetos',{token:token()});if(!r.sucesso){toast(r.mensagem||'Entre como arquiteto para usar esta função.');return;}const projects=r.projetos||[];if(!projects.length){modal('Adicionar ao projeto',`<div class="arq6-empty"><p>Crie seu primeiro projeto antes de especificar produtos.</p><a class="arq6-btn gold" href="ARQSELECT_ARQUITETO_SOLICITAR.html">Criar projeto</a></div>`);return;}const b=modal('Escolha o projeto',`<div class="arq6-list">${projects.map(p=>`<button class="arq6-row" data-project="${esc(p.id)}"><span class="arq6-badge">${esc(p.status||'Projeto')}</span><span><b>${esc(p.projeto||p.id)}</b><br><small>${esc([p.cidade,p.estado].filter(Boolean).join(' · '))}</small></span><span>Selecionar →</span></button>`).join('')}</div>`);b.querySelectorAll('[data-project]').forEach(btn=>btn.onclick=()=>{document.getElementById('arq6Modal').hidden=true;onChoose(btn.dataset.project);});}
  function productInfoFrom(el,id){const card=el?.closest('.arq-product-card');const detail=document.querySelector('.arq-product-info');return {id:id||new URLSearchParams(location.search).get('id')||'',nome:(card?.querySelector('h3')?.textContent||detail?.querySelector('h1')?.textContent||document.querySelector('h1')?.textContent||'Produto').trim(),categoria:(card?.querySelector('.arq-product-card__cat')?.textContent||detail?.querySelector('.arq-kicker')?.textContent?.split('·')[0]||'').trim(),imagem:card?.querySelector('img')?.getAttribute('src')||document.querySelector('.arq-gallery-main img')?.getAttribute('src')||'',url:location.href};}
  function addToProject(info){if(role()!=='ARQUITETO'&&!['ADMIN'].includes(role())){toast('Entre como arquiteto para adicionar produtos ao projeto.');return;}chooseProject(projectId=>{const body=modal('Adicionar à especificação',`<form id="arq6SpecForm" class="arq6-form"><label class="full">Produto<input name="nome" value="${esc(info.nome)}" readonly></label><label>Quantidade<input name="quantidade" placeholder="Ex.: 80"></label><label>Unidade<select name="unidade"><option>m²</option><option>un</option><option>ml</option><option>kit</option><option>cx</option></select></label><label>Ambiente<input name="ambiente" placeholder="Ex.: sala e dormitórios"></label><label>Medidas<input name="medidas" placeholder="Ex.: 182 × 1220 mm"></label><label>Acabamento<input name="acabamento"></label><label>Cor<input name="cor"></label><label class="full">Observações<textarea name="observacoes" rows="3"></textarea></label><div class="full arq6-actions"><button class="arq6-btn gold" type="submit">Adicionar ao projeto</button></div></form>`);const f=body.querySelector('form');f.onsubmit=async e=>{e.preventDefault();const btn=f.querySelector('button');btn.disabled=true;const d=Object.fromEntries(new FormData(f));const r=await api('portal_especificacao_salvar',{...d,token:token(),projetoId:projectId,produtoId:info.id,categoria:info.categoria,imagem:info.imagem,url:info.url},'POST');btn.disabled=false;toast(r.mensagem||'Operação concluída.');if(r.sucesso){track('ADICIONAR_PROJETO','PRODUTO',info.id);document.getElementById('arq6Modal').hidden=true;}};});}
  function requestSample(info){if(role()!=='ARQUITETO'){toast('Entre como arquiteto para solicitar uma amostra.');return;}chooseProject(projectId=>{const body=modal('Solicitar amostra',`<form id="arq6SampleForm" class="arq6-form"><label class="full">Produto<input value="${esc(info.nome)}" readonly></label><label>Tipo<select name="tipoAmostra"><option>Amostra física</option><option>Catálogo físico</option><option>Mostruário</option><option>Amostra de acabamento</option></select></label><label>Quantidade<input name="quantidade" value="1"></label><label>Cidade<input name="cidade" required></label><label>Local de entrega<input name="localEntrega" placeholder="Escritório / obra"></label><label class="full">Observações<textarea name="observacoes" rows="3"></textarea></label><div class="full arq6-actions"><button class="arq6-btn gold" type="submit">Enviar solicitação</button></div></form>`);const f=body.querySelector('form');f.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f));const r=await api('portal_amostra_solicitar',{...d,token:token(),projetoId:projectId,produtoId:info.id,produto:info.nome,categoria:info.categoria},'POST');toast(r.mensagem||'Operação concluída.');if(r.sucesso){track('SOLICITAR_AMOSTRA','PRODUTO',info.id);document.getElementById('arq6Modal').hidden=true;}};});}
  async function technicalDocs(info){const r=await api('public_documentos_tecnicos',{produtoId:info.id});const docs=r.documentos||[];const body=docs.length?`<div class="arq6-list">${docs.map(d=>`<a class="arq6-row" href="${esc(d.URL)}" target="_blank" rel="noopener" data-tech="${esc(d.ID)}"><span class="arq6-badge">${esc(d.TIPO||'Documento')}</span><span><b>${esc(d.TITULO)}</b><br><small>${esc(d.DESCRICAO||d.VERSAO||'Arquivo técnico')}</small></span><span>Baixar ↗</span></a>`).join('')}</div>`:`<div class="arq6-empty"><b>Arquivos técnicos ainda não publicados.</b><p class="arq6-muted">A ARQSELECT poderá solicitar a ficha diretamente ao fornecedor durante a cotação.</p></div>`;const root=modal('Biblioteca técnica',body);root.querySelectorAll('[data-tech]').forEach(a=>a.onclick=()=>track('DOWNLOAD_TECNICO','PRODUTO',info.id,a.dataset.tech));}
  function enhanceProducts(root=document){if(!root.querySelectorAll)return;root.querySelectorAll('.arq-product-card').forEach(card=>{if(card.dataset.arq6)return;card.dataset.arq6='1';const id=card.querySelector('[data-quote]')?.dataset.quote||card.querySelector('[data-fav]')?.dataset.fav;if(!id)return;const body=card.querySelector('.arq-product-card__body');if(body&&role()==='ARQUITETO'){const b=document.createElement('button');b.className='arq6-btn arq6-product-card-action';b.type='button';b.textContent='+ Adicionar ao projeto';b.onclick=e=>{e.preventDefault();addToProject(productInfoFrom(card,id));};body.append(b);}});
  }
  function enhanceProductDetail(){const params=new URLSearchParams(location.search),staticId=(location.pathname.match(/produto-(lux-\d+)\.html$/i)||[])[1]||'',id=params.get('id')||document.body.dataset.productId||staticId.toUpperCase()||'';const stack=document.querySelector('.arq-cta-stack');if(!stack||stack.dataset.arq6)return false;stack.dataset.arq6='1';const info=productInfoFrom(stack,id);const add=document.createElement('button');add.className='arq-btn';add.type='button';add.textContent='＋ Adicionar ao projeto';add.onclick=()=>addToProject(info);const sample=document.createElement('button');sample.className='arq-btn';sample.type='button';sample.textContent='Solicitar amostra';sample.onclick=()=>requestSample(info);const docs=document.createElement('button');docs.className='arq-btn';docs.type='button';docs.textContent='Ficha técnica / BIM / Downloads';docs.onclick=()=>technicalDocs(info);stack.prepend(docs);stack.prepend(sample);stack.prepend(add);productSchema(info);track('VISUALIZACAO','PRODUTO',info.id);return true;}
  function productSchema(info){
    if(!info||!info.nome||document.getElementById('arq6ProductSchema'))return;
    const desc=(document.querySelector('.arq-product-info p,.arq-product-lead,.arq-product-card__desc')?.textContent||'').trim();
    let image='';try{if(info.imagem)image=new URL(info.imagem,location.href).href;}catch(_){image='';}
    const data={'@context':'https://schema.org','@type':'Product',name:info.nome,category:info.categoria||undefined,description:desc||undefined,image:image?[image]:undefined,url:location.href};
    Object.keys(data).forEach(k=>data[k]===undefined&&delete data[k]);
    const tag=document.createElement('script');tag.type='application/ld+json';tag.id='arq6ProductSchema';tag.textContent=JSON.stringify(data);document.head.append(tag);
  }
  function enhanceSupplierInvite(){
    if(role()!=='ARQUITETO'&&role()!=='ADMIN')return false;
    const connect=document.getElementById('connectProfile'),id=new URLSearchParams(location.search).get('id');
    if(!connect||!id||document.getElementById('arq6InviteSupplier'))return false;
    const b=document.createElement('button');b.id='arq6InviteSupplier';b.className='arq-btn arq-btn--gold';b.type='button';b.textContent='Convidar para projeto';
    b.onclick=()=>chooseProject(async projectId=>{const r=await api('portal_fornecedor_convidar',{token:token(),projetoId,fornecedorId:id},'POST');toast(r.mensagem||'Operação concluída.');if(r.sucesso)track('ABRIR_FORNECEDOR','PERFIL',id);});
    connect.insertAdjacentElement('afterend',b);return true;
  }
  function projectLinks(){if(!token())return;const page=location.pathname.split('/').pop().toLowerCase();if(!/(dashboard|projeto|especific|amostra|pedido|proposta|board|oportun|chat|favorit|suporte|analytics|biblioteca|assistente|cliente)/.test(page))return;const host=document.querySelector('main,.wrap,.arq6-shell');if(!host||document.getElementById('arq6QuickNav'))return;const nav=document.createElement('nav');nav.id='arq6QuickNav';nav.className='arq6-project-nav';nav.setAttribute('aria-label','Workspace ARQSELECT');const items=role()==='ADMIN'?[['Admin','admin.html'],['Descobrir','descobrir.html'],['Negócios','painel-negocios.html'],['Operação','admin-commerce.html'],['Marketplace','explorar.html'],['Projetos','ARQSELECT_ARQUITETO_PROJETOS.html'],['Pedidos','pedidos.html'],['Feed','feed.html']]:role()==='FORNECEDOR'?[['Descobrir','descobrir.html'],['Negócios','painel-negocios.html'],['Oportunidades','oportunidades.html'],['Propostas','propostas-portal.html'],['Pedidos','pedidos.html'],['Biblioteca','biblioteca-tecnica.html'],['Analytics','analytics-fornecedor.html'],['Chat','chat.html']]:role()==='PRESTADOR'?[['Painel','dashboard-prestador.html'],['Descobrir','descobrir.html'],['Negócios','painel-negocios.html'],['Oportunidades','oportunidades-servicos.html'],['Propostas','propostas-servicos.html'],['CRM','crm-prestador.html'],['Execução','execucao-servicos.html'],['Agenda','agenda-prestador.html'],['Portfólio','portfolio-prestador.html'],['Chat','chat.html']]:[['Projetos','ARQSELECT_ARQUITETO_PROJETOS.html'],['Hub do projeto','sala-projeto.html'],['Descobrir','descobrir.html'],['Negócios','painel-negocios.html'],['Especificações','especificacoes.html'],['Comparar propostas','comparar-propostas.html'],['Amostras','amostras.html'],['Clientes','clientes-projeto.html'],['Pedidos','pedidos.html'],['Boards','boards.html'],['Assistente','assistente.html']];nav.innerHTML=items.map(([t,h])=>`<a class="arq6-btn" href="${h}">${t}</a>`).join('');host.prepend(nav);}
  function init(){projectLinks();enhanceProducts();const mo=new MutationObserver(records=>{records.forEach(r=>r.addedNodes.forEach(n=>{if(n.nodeType===1){enhanceProducts(n);if(/produto(?:-lux-\d+)?\.html$/i.test(location.pathname))enhanceProductDetail();if(/fornecedor\.html$/i.test(location.pathname))enhanceSupplierInvite();}}));});mo.observe(document.body,{childList:true,subtree:true});if(/produto(?:-lux-\d+)?\.html$/i.test(location.pathname))setTimeout(enhanceProductDetail,150);if(/fornecedor\.html$/i.test(location.pathname)){const id=new URLSearchParams(location.search).get('id');if(id)track('VISUALIZACAO','PERFIL',id);setTimeout(enhanceSupplierInvite,250);} }
  document.addEventListener('click',e=>{const f=e.target.closest?.('[data-fav]');if(f)track('SALVAR','PRODUTO',f.dataset.fav||'');},{passive:true});
  window.ARQSELECT6={build:'2026.09.20.600',api,token,role,esc,toast,modal,track,addToProject,requestSample,technicalDocs,chooseProject};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
